//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDiProgrammingTestProject.Core.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPersonGPA
    {
        public int GPAID { get; set; }
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public double GPA { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Enabled { get; set; }
    }
}
